const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';
const SET_ALLIES = 'SET_ALLIES';
const SET_ALERT = 'SET_ALERT';
const CLEAR_SINGLE_ALERT = 'CLEAR_SINGLE_ALERT';
const CLEAR_ALL_ALERTS = 'CLEAR_ALL_ALERTS';
const SET_PATHNAME = 'SET_PATHNAME';

export { SET_ACCOUNT_INFO, SET_ALLIES, SET_ALERT, CLEAR_SINGLE_ALERT, CLEAR_ALL_ALERTS, SET_PATHNAME };