const ACCOUNT_INFO_TO_STATE = 'ACCOUNT_INFO_TO_STATE';
const ALLIES_TO_STATE = 'ALLIES_TO_STATE';
const ALERT_TO_STATE = 'ALERT_TO_STATE';
const CLEAR_SINGLE_ALERT_FROM_STATE = 'CLEAR_SINGLE_ALERT_FROM_STATE';
const CLEAR_ALL_ALERTS_FROM_STATE = 'CLEAR_ALL_ALERTS_FROM_STATE';
const PATHNAME_TO_STATE = 'PATHNAME_TO_STATE';

export { ACCOUNT_INFO_TO_STATE, ALLIES_TO_STATE, ALERT_TO_STATE, CLEAR_SINGLE_ALERT_FROM_STATE, CLEAR_ALL_ALERTS_FROM_STATE, PATHNAME_TO_STATE };