const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO';
const SET_ALLIES = 'SET_ALLIES';
const SET_ALERT = 'SET_ALERT';
const CLEAR_SINGLE_ALERT = 'CLEAR_SINGLE_ALERT';
const CLEAR_ALL_ALERTS = 'CLEAR_ALL_ALERTS';
const SET_PATHNAME = 'SET_PATHNAME';
const INIT_WEB3 = 'INIT_WEB3';
const SET_CONTRACT_INSTANCE = 'SET_CONTRACT_INSTANCE';

export { SET_ACCOUNT_INFO, SET_ALLIES, SET_ALERT, CLEAR_SINGLE_ALERT, CLEAR_ALL_ALERTS, SET_PATHNAME, INIT_WEB3, SET_CONTRACT_INSTANCE };